### ISSUE TITLE
ReferenceError: __name is not defined

### ISSUE THREAD

**Issue by Uninen** [esbuild-kit/tsx#113]
### Bug description

I'm trying to use Playwright screenshot function w/ tsx from command line. This has worked in previous versions and works with tsm but doesn't work w/ tsx.

### Reproduction

```
// test.ts

import { chromium } from 'playwright-chromium'
;(async () => {
  const url = 'https://www.unessa.net'

  const browser = await chromium.launch({
    headless: true,
  })
  const context = await browser.newContext()
  const page = await context.newPage()

  await page.goto(url)
  await page.screenshot({
    path: 'test-screenshot.png',
    fullPage: true,
  })

  await browser.close()
})()
```

Runing `npx tsx src/testfn.ts` produces following error:

```
page.screenshot: ReferenceError: __name is not defined
    at eval (eval at evaluate (:190:30), <anonymous>:1:102)
    at UtilityScript.evaluate (<anonymous>:192:17)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
=========================== logs ===========================
taking page screenshot
============================================================
    at null.<anonymous> (/../test.ts:12:14)
```

### Environment

```shell
<!--
  Run and paste the output of:
  
  npx envinfo --system --npmPackages tsx --binaries
  ```
-->

```
  System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 83.13 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Watchman: 2022.09.19.00 - /opt/homebrew/bin/watchman
  npmPackages:
    tsx: 3.9.0 => 3.9.0 
```
```


### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by Uninen** [comment]
Yes, the @esbuild-kit/core-utils version is 2.3.2. Pushed a small repro here: https://github.com/Uninen/tsx-issue-113-repro

**Comment by CircleCurve** [comment]
I'm also facing this issue. When will this gonna be fixed ?  Or how can we fix it ??

**Comment by privatenumber** [comment]
See comment above.

**Comment by CircleCurve** [comment]
OK. Thanks. It seems like the issue still in pending and waiting the esbuild to resolve with it??

**Comment by privatenumber** [comment]
Yep, hence the blocked tag on this Issue.

**Comment by loynoir** [comment]
reproduce.mts
```ts
// @ts-check
import playwright from 'playwright-core'
const browser = await playwright.firefox.launch()
const browserContext = await browser.newContext()
const page = await browserContext.newPage()
await page.goto('http://127.0.0.1:1234/')
await page.waitForFunction('() => true')
await page.close()
await browserContext.close()
await browser.close()
```

```
node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^

page.waitForFunction: __name is not defined
@debugger eval code line 195 > eval:1:95
evaluate@debugger eval code:197:17
@debugger eval code:1:44

    at <anonymous> (/path/to/reproduce.mts:7:12) {
  name: 'Error'
}

Node.js v18.15.0
```

@privatenumber

- Are there any workarounds? 
- Can you provide a code, generated by esbuild, with same underlying problem, throws `__name is not defined`?
- Seems `esbuild` has low interest to fix, does `swc` have same underlying problem? What about change `tsx` to use `swc`?

**Comment by loynoir** [comment]
Workaround, using `ts-node`, `swc` seems does not have this problem.

Related https://github.com/TypeStrong/ts-node/issues/2000

```sh
$ npm exec -- tsc --showConfig > tsconfig.tsnode.json
$ npm exec -- ts-node --project tsconfig.tsnode.json --esm --swc ./reproduce.mts && echo OK
OK
```

**Comment by loynoir** [comment]
Workaround updated

1. use `--loader @esbuild-kit/esm-loader`, which support `tsconfig.paths`

```
$ node --loader @esbuild-kit/esm-loader ./reproduce.mts && echo OK
```

2. use `ts-node`, which does not support `tsconfig.paths`, does not support typescript 5.0 tsconfig.extends array

```sh
$ npm exec -- tsc --showConfig > tsconfig.tsnode.json
$ npm exec -- ts-node --project tsconfig.tsnode.json --esm --swc ./reproduce.mts && echo OK
OK
```

**Comment by privatenumber** [comment]
> But I'm still curious about what is the esbuild underlying problem, very appreciated for any explanation.

Read https://github.com/esbuild-kit/tsx/issues/113#issuecomment-1274694577

**Comment by loynoir** [comment]
@privatenumber 

> Read https://github.com/esbuild-kit/tsx/issues/113#issuecomment-1274694577

I read before I said that. 

But I don't understand how `ReferenceError: __name is not defined` is generated.

---

> I filed a feature request to only apply __name when the function is actually renamed

I think should filed with BUG, with a small example throws `ReferenceError: __name is not defined`.

If a bundler generate different runtime output, when `minify: false`,  I think it must be a BUG.

**Comment by privatenumber** [comment]
It's kind of both.

- tsx doesn't need to apply esbuild to all files but it currently does.
- esbuild doesn't need to apply `__name` to all functions but it currently does.

**Comment by jd-solanki** [comment]
Can we get this in #267?

**Comment by privatenumber** [comment]
This specific problem is blocked by esbuild—out of my hands.

However, the 2 issues under "Optimize dependency transformations" on the Roadmap will address this from happening in dependencies.

**Comment by jd-solanki** [comment]
@privatenumber Is there any issue in esbuild I can watch for?

**Comment by privatenumber** [comment]
It's linked in the conversation above

**Comment by privatenumber** [comment]
The specific problem with `playwright-core` will be fixed via https://github.com/esbuild-kit/tsx/pull/365.

However, I'll leave this open because it's not completely fixed for all cases (e.g a dependency module uses both ESM and `eval()`).

**Comment by vanya2h** [comment]
Just discovered this problem with webpack's terser plugin, so it's more likely related to all kinds of minifications. 

Btw, still can't figure out how to workaround this and switching to ts-node for my scripts execution (I'm using webpack with terser not as Cli but programmatically)

**Comment by privatenumber** [comment]
See comment & PR above.

**Comment by niieani** [comment]
Experiencing the same problem using puppeteer.

**Comment by privatenumber** [comment]
With https://github.com/privatenumber/tsx/releases/tag/v4.0.0 released, this will likely no longer be an issue in the majority of cases.

Hope it works well for yall!

Keeping this issue open but labelled "Blocked" because the root issue is in esbuild.

**Comment by cjroebuck** [comment]
Here's a repro with puppeteer:

``` name=tsxrepro.ts
import puppeteer from "puppeteer";

let run = async () => {
  let url = "https://www.google.com";
  let browser = await puppeteer.launch({
    headless: false,
    dumpio:true,
    args: [
      "--no-sandbox",
    ],
  });
  let page = await browser.newPage();
  await page.goto(url);
  await page.evaluate(async function () {
      let sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));
      await sleep(2000);
  })
  await page.screenshot();
  await browser.close();
}


run().then(()=>{ console.log('done')}).catch((e)=>{console.log(e)}); 


```

`npx tsx tsxrepro.tsx`

```
Error [ReferenceError]: __name is not defined
    at evaluate (evaluate at run (file:///Users/dev/tsxrepro.ts:1:358), <anonymous>:0:28)
    at ExecutionContext.#evaluate (/Users/dev/node_modules/puppeteer/node_modules/puppeteer-core/src/cdp/ExecutionContext.ts:313:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ExecutionContext.evaluate (/Users/dev/node_modules/puppeteer/node_modules/puppeteer-core/src/cdp/ExecutionContext.ts:168:12)
    at IsolatedWorld.evaluate (/Users/dev/node_modules/puppeteer/node_modules/puppeteer-core/src/cdp/IsolatedWorld.ts:151:12)
    at CdpFrame.evaluate (/Users/dev/node_modules/puppeteer/node_modules/puppeteer-core/src/api/Frame.ts:489:12)
    at CdpPage.evaluate (/Users/dev/node_modules/puppeteer/node_modules/puppeteer-core/lib/esm/puppeteer/api/Page.js:717:20)
    at run (/Users/dev/tsxrepro.ts:14:3)
```

**Comment by privatenumber** [comment]
@cjroebuck

Just to clarify, the v4 release addresses this issue from occurring only in dependency code.

The issue you're facing is due to user-land code in the function passed into `page.evaluate` (or `eval`), which is why this issue is still open and labeled as _Blocked_.

I want to point out that [`eval` is not supported by esbuild](https://github.com/privatenumber/tsx/#does-it-have-any-limitations). However, this specific issue would be addressed by https://github.com/evanw/esbuild/issues/2605.

It's very hacky, and I don't recommend it, but you can work around the error by add the following code snippet to the top of your app:

```ts
const { toString } = Function.prototype;
Function.prototype.toString = function() {
    const stringified = Reflect.apply(toString, this, arguments);
    return `function () {
        const __name = (target, value) => Object.defineProperty(target, "name", { value, configurable: true });
        return Reflect.apply(${stringified}, this, arguments);
    }`;
};
```

**Comment by privatenumber** [comment]
Locking this thread since the problem is well-understood, and further investigation isn't needed.

If anyone comes across this, note that the issue is blocked by https://github.com/evanw/esbuild/issues/2605.
