### ISSUE TITLE
process.stdin.write is not a function

### ISSUE THREAD

**Issue by stephenh** [esbuild-kit/tsx#117]
### Bug description

I'm running tsx in watch mode and getting this error on file changes/reloads:

```
TypeError: process.stdin.write is not a function
graphql-service-graphql-1  |     at process.e (/home/node/app/node_modules/tsx/dist/preflight.cjs:7:24)
graphql-service-graphql-1  |     at process.emit (node:events:527:28)
graphql-service-graphql-1  |     at process.emit (/home/node/app/node_modules/tsx/dist/suppress-warnings.cjs:1:307)
graphql-service-graphql-1  |     at Signal.callbackTrampoline (node:internal/async_hooks:130:17)
```

It doesn't happen every time, but maybe 50% of the time.

I'm invoking tsx watch in a docker container using node v16.15.1 and also v18.10.0:

```
    command: ./node_modules/.bin/tsx watch --inspect=0.0.0.0:9229 src/server.ts
```

### Reproduction

I don't have a reproduction

### Environment

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (24) x64 12th Gen Intel(R) Core(TM) i9-12900K
    Memory: 4.89 GB / 31.09 GB
    Container: Yes
    Shell: 3.5.1 - /usr/bin/fish
  Binaries:
    Node: 18.10.0 - ~/.temp/xfs-5c32e88c/node
    Yarn: 3.2.3 - ~/.temp/xfs-5c32e88c/yarn
    npm: 8.19.2 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 20201227.082254.0 - /usr/local/bin/watchman
  npmPackages:
    tsx: ^3.10.2 => 3.10.2 
```
```


### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment]
Thanks for the quick catch. Should be fixed in the above release.
