### ISSUE TITLE
Regression between 3.10.1 and 3.10.2

### ISSUE THREAD

**Issue by GauBen** [esbuild-kit/tsx#122]
### Bug description

Hey!

There seems to be a regression between tsx versions 3.10.1 and 3.10.2: the watcher doesn't properly kill the process when [prisma](https://www.prisma.io/) is used.

### Reproduction

```ts
import { PrismaClient } from '@prisma/client'; // @prisma/client 4.5.0 (latest)
import express from 'express'; // express 4.18.2 (latest)

// Instanciating Prisma is enough for the watcher not to kill the child process correctly
const prisma = new PrismaClient();

const api = express();
api.get('/', (_req, res) => {
  res.send('<h1>Hello World!</h1>');
});
api.listen(4000);
```

Run this with `tsx watch ./index.ts`.

No problem with tsx 3.10.1, but tsx 3.10.2+ causes this error to be raised on restart:

```
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::4000
    at __node_internal_captureLargerStackTrace (node:internal/errors:484:5)
    ...
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 4000
}
```

### Environment

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04 LTS 22.04 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 9 5900HX with Radeon Graphics
    Memory: 5.81 GB / 11.68 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.11.0 - ~/.volta/tools/image/node/18.11.0/bin/node
    Yarn: 4.0.0-rc.25 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 8.19.2 - ~/.volta/tools/image/node/18.11.0/bin/npm
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment]
Please provide a minimal reproduction repository.

I can't get your reproduction to run and I'm not familiar with Prisma:
```
$ pnpm tsx index.mjs
/node_modules/.pnpm/@prisma+client@4.5.0/node_modules/.prisma/client/index.js:3
    throw new Error(
          ^

Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
    at PrismaClient (/node_modules/.pnpm/@prisma+client@4.5.0/node_modules/.prisma/client/index.js:3:11)
    at file:///index.mjs:5:16
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:526:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
```
