### ISSUE TITLE
import() function is parsed wrong

### ISSUE THREAD

**Issue by zen0822** [esbuild-kit/tsx#192]
### Bug description

when type the code in (node_modules\node-plop\src\node-plop.js), it would show follow error
```js
const joinedPath = path.join(plopfilePath, plopFileName);
const plopFileExport = await import(pathToFileURL(joinedPath).href);
```
error
```bash
[PLOP] Something went wrong with reading your plop file TypeError: (0 , import_url.pathToFileURL).then is not a function
    at nodePlop (c:\Users\zhiming.huang\git\kun\node_modules\.pnpm\node-plop@0.31.1\node_modules\node-plop\src\node-plop.js:268:41)
    at run (c:\Users\zhiming.huang\git\kun\node_modules\.pnpm\plop@3.1.2\node_modules\plop\src\plop.js:56:18)
    at Liftoff.<anonymous> (c:\Users\zhiming.huang\git\kun\plop\index.ts:22:12)
    at Liftoff.Liftoff.prepare (c:\Users\zhiming.huang\git\kun\node_modules\.pnpm\liftoff@4.0.0\node_modules\liftoff\index.js:255:6)
    at <anonymous> (c:\Users\zhiming.huang\git\kun\plop\index.ts:14:6)
    at Object.<anonymous> (c:\Users\zhiming.huang\git\kun\plop\index.ts:24:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.F (C:\Users\zhiming.huang\git\kun\node_modules\.pnpm\@esbuild-kit+cjs-loader@2.4.2\node_modules\@esbuild-kit\cjs-loader\dist\index.js:1:941)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
```

the parsed code
```js
const plopFileExport = await import((0, import_url.pathToFileURL).then((mod) => {
  const exports = Object.keys(mod);

  if (exports.length === 1 && exports[0] === 'default' && mod.default.__esModule) {
    return mod.default
  }

  return mod
})(joinedPath).href);
```

when I type the code is fine
```js
const joinedPath = pathToFileURL(path.join(plopfilePath, plopFileName)).href;
console.log(joinedPath)
const plopFileExport = await import(joinedPath);
```

the parsed code
```js
const plopFileExport = await import(joinedPath).then((mod) => {
  const exports = Object.keys(mod);
  if (exports.length === 1 && exports[0] === 'default' && mod.default.__esModule) {
    return mod.default
  } return mod
});
```

Is it esbuild wrong?

### Reproduction

Reproduction url

https://stackblitz.com/edit/node-sfdmum?file=plop/index.ts

### Environment

```shell
node 18+
esno ^0.16.3
```

### Can you work on a fix?

- [ ] I’m interested in opening a pull request to address this issue.

**Comment by drevantonder** [comment]
This is also occurring when trying to use `tsx` to run a custom server for next.js using `server.ts` rather than `server.js`: https://nextjs.org/docs/pages/building-your-application/configuring/custom-server

```
TypeError: (0 , _url.pathToFileURL).then is not a function
    at loadConfig (/home/node/node_modules/.pnpm/next@13.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/config.js:501:58)
    at <anonymous> (/home/node/node_modules/.pnpm/next@13.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next.js:99:40)
```

**Comment by qwertyuiop6** [comment]
I'm also experiencing it in nextjs custom server ```tsx server.ts```


``` TypeError: (0 , _url.pathToFileURL).then is not a function at loadConfig (/root/code/projects/dst-wx-admin/node_modules/.pnpm/next@13.4.9_@babel+core@7.21.4_react-dom@18.2.0_react@18.2.0_sass@1.63.6/node_modules/next/dist/server/config.js:554:58) at Proxy.standaloneHandler (/root/code/projects/dst-wx-admin/node_modules/.pnpm/next@13.4.9_@babel+core@7.21.4_react-dom@18.2.0_react@18.2.0_sass@1.63.6/node_modules/next/dist/server/next.js:255:44) ``` 


 Any solution?

**Comment by privatenumber** [comment]
Filed a bug in es-module-lexer:
https://github.com/guybedford/es-module-lexer/issues/156

**Comment by privatenumber** [comment]
Should be fixed now.

Try upgrading `@esbuild-kit/core-utils` via:
```sh
npm update @esbuild-kit/core-utils
```
