### ISSUE TITLE
Constructor parameter properties vs 'this' in field initializers

### ISSUE THREAD

**Issue by yoursunny** [esbuild-kit/tsx#280]
### Bug description

When a field initializer refers to a property created from parameter properties on the constructor, **tsx** complains that the property is `undefined`.
In both **tsm** and **tsc**, the same script can work correctly.

```shell
ubuntu@node:~/x$ ./node_modules/.bin/tsx main.ts 
/home/ubuntu/x/main.ts:9
  public readonly n = this.a.n;
                             ^


TypeError: Cannot read properties of undefined (reading 'n')
    at B.<instance_members_initializer> (/home/ubuntu/x/main.ts:9:30)
    at B (/home/ubuntu/x/main.ts:6:3)
    at <anonymous> (/home/ubuntu/x/main.ts:12:11)
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    at async CustomizedModuleLoader.import (node:internal/modules/esm/loader:228:24)
    at async loadESM (node:internal/process/esm_loader:40:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.5.0

ubuntu@node:~/x$ ./node_modules/.bin/tsm main.ts 
(node:1158422) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
B { a: { n: 1 }, n: 1 }
```

### Reproduction

**main.ts**

```ts
interface A {
  n: number;
}

class B {
  constructor(public readonly a: A) {
  }

  public readonly n = this.a.n;
}

const b = new B({ n: 1 });
console.log(b);
```

**package.json**

```json
{
  "private": true,
  "type": "module",
  "packageManager": "pnpm@8.6.11",
  "dependencies": {
    "tsm": "^2.3.0",
    "tsx": "^3.12.7",
    "typescript": "^5.1.6"
  }
}
```

**tsconfig.json**

```jsonc
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "importHelpers": true,
    "module": "es2022",
    "moduleResolution": "Node",
    "noEmit": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noUncheckedIndexedAccess": true,
    "noUnusedLocals": true,
    "strict": true,
    "target": "ES2022"
  },
  "include": [
    "**/*.ts"
  ]
}
```

### Environment

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (14) x64 AMD EPYC 7532 32-Core Processor
    Memory: 19.84 GB / 31.34 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.5.0 - /usr/bin/node
    npm: 9.8.0 - /usr/bin/npm
  npmPackages:
    tsx: ^3.12.7 => 3.12.7
```

### Can you work on a fix?

- [ ] I’m interested in opening a pull request to address this issue.

**Comment by privatenumber** [comment]
Thanks for the issue. Looks like an esbuild bug so I filed https://github.com/evanw/esbuild/issues/3385

**Comment by privatenumber** [comment]
As Evan explained in https://github.com/evanw/esbuild/issues/3385#issuecomment-1720244722, this is actually an error in your code.

If you run `tsc` (v5.2) with `noEmit` removed, and run that output with `node`, it gives the same error.

`tsm` is using an older version of esbuild before the `useDefineForClassFields` default value changed.

Set `useDefineForClassFields: false` for the legacy behavior, but note it behaves differently from native JS classes.
