### ISSUE TITLE
`Cannot read properties of undefined (reading '__esModule')` when `import()` a TS file with `export = undefined`

### ISSUE THREAD

**Issue by jcbhmr** [esbuild-kit/tsx#281]
### Bug description

```sh
Error: Cannot read properties of undefined (reading '__esModule')
    at file:///home/projects/node-f7sexx/index.mts
    at async ESMLoader.import (https://nodef7sexx-30jt.w-credentialless.staticblitz.com/blitz.d5d65229.js:213:4862)
    at async i.loadESM (https://nodef7sexx-30jt.w-credentialless.staticblitz.com/blitz.d5d65229.js:60:915)
    at async handleMainPromise (https://nodef7sexx-30jt.w-credentialless.staticblitz.com/blitz.d5d65229.js:168:264)
```

When dynamically importing a CommonJS TypeScript file, it appears as though there isn't a guard like `mod && mod.__esModule` and instead it appears to be just `mod.__esModule` which fails if `module.exports` of the `require()`-ed module is `undefined`. Solution is probably do something similar-ish to do what TypeScript does by default:

https://www.npmjs.com/package/tslib?activeTab=code
```js
export function __importStar(mod) {
  if (mod && mod.__esModule) return mod;
  var result = {};
  if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
  __setModuleDefault(result, mod);
  return result;
}

export function __importDefault(mod) {
  return (mod && mod.__esModule) ? mod : { default: mod };
}
```

### Reproduction

```ts
// index.mts
let lib = await import("./lib.js")
console.log(lib);
```
```ts
// lib.ts (inside type=commonjs package.json)
export = undefined;
```

https://stackblitz.com/edit/tsx-esmodule-brokey?file=index.mts,package.json,lib.ts

### Environment

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.10 - /usr/local/bin/pnpm
  npmPackages:
    tsx: ^3.12.1 => 3.12.1
```

### Can you work on a fix?

- [ ] I’m interested in opening a pull request to address this issue.

**Comment by jcbhmr** [comment]
It would appear that it's here?
https://github.com/esbuild-kit/core-utils/blob/bdf4ef3d701288fbf8cda6f3564b61fe86defcd0/src/transform/transform-dynamic-import.ts#L8
```js
const checkEsModule = `.then((mod)=>{
	const exports = Object.keys(mod);
	if(
		exports.length===1&&exports[0]==='default'&&mod.default.__esModule
	){
		return mod.default
	}
	return mod
})`.replace(/[\n\t]+/g, '');
```

from https://github.com/search?q=org%3Aesbuild-kit%20__esModule&type=code

👇 which could be changed to

```js
mod.default?.__esModule
// OR
mod.default&&mod.default.__esModule
```
