### ISSUE TITLE
tsx don't support typescript@5 decorator

### ISSUE THREAD

**Issue by sirenkovladd** [esbuild-kit/tsx#287]
### Problem

The second attribute (context) is different from typescript@5

```sh
❯ npx tsx 287.ts
Wrapping {} a
<cut>/287.ts:3
  ctx.addInitializer(function W() {
      ^


TypeError: ctx.addInitializer is not a function
    at wrap (<cut>/287.ts:3:7)
    at __decorateClass (<cut>/287.ts:2:387)
    at <anonymous> (<cut>/287.ts:10:10)
    at Object.<anonymous> (<cut>/287.ts:13:15)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Object.F (<cut>/node_modules/@esbuild-kit/cjs-loader/dist/index.js:1:941)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:165:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)

Node.js v20.5.0
```

### Expected behavior

```sh
❯ npx tsc && node built/287.js
Wrapping undefined {
  kind: 'field',
  name: 'a',
  static: false,
  private: false,
  access: { has: [Function: has], get: [Function: get], set: [Function: set] },
  addInitializer: [Function (anonymous)]
}
Initialized A {} undefined
```

### URL

https://stackblitz.com/edit/node-zvd45k

### Version

3.12.7

### Node.js version

v20.5.0 | v18.17.0

### Package manager

npm

### Operating system

Linux

### It would be amazing if you can contribute to the project!

- [X] I plan to open a pull request for this issue.

**Comment by sirenkovladd** [comment]
https://github.com/evanw/esbuild/issues/104

**Comment by privatenumber** [comment]
Closing this as there's nothing to be done on tsx's side aside from upgrading esbuild when implemented.

I appreciate this issue for anyone else searching though.
