### ISSUE TITLE
Css import error

### ISSUE THREAD

**Issue by jfstephe** [esbuild-kit/tsx#290]
### Problem

I have a React (v18.2.0) component which I'd like to import some css (css modules or vanilla). Everything works as expected until I add my import css line:

`import cssModule from "test.module.css";`

But I get the error:

`
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".css" for .....\test.module.css
`
via the esm loader.

### Expected behavior

Well I was hoping this would 'just work' but after reading the docs I think tsx is doing what it 'should' in that it's only concerned about transpiling ts/js formats.

I feel that I'm missing something as I don't understand why others aren't having the same issue. I've tried to create a repro of the issue using stackblitz with the default typescript create react app:

`npx create-react-app my-app --template typescript`

I also changed the package.json "type" to "module", but that was the only change I made.

**NOTE: This step first in the below**
cd my-app2/

```
~/projects/node-q5mgup 1s
❯ cd my-app2/

~/projects/node-q5mgup/my-app2
❯ tsx ./src/index.tsx
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".css" for /home/projects/node-q5mgup/my-app2/src/index.css
    at TypeError.get (https://nodeq5mgup-loqu.w-credentialless.staticblitz.com/blitz.33975f1d.js:67:7048)
    at Object.triggerUncaughtException (https://nodeq5mgup-loqu.w-credentialless.staticblitz.com/blitz.33975f1d.js:334:379543)
    at i.loadESM (node:internal/process/esm_loader:60:983)
    at async handleMainPromise (node:internal/modules/run_main:168:264) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

```

I did find out that it also works out of the box with json files which was nice :-).

### Minimal reproduction URL

https://stackblitz.com/edit/node-q5mgup?file=my-app2%2Fpackage.json

### Version

3.12.7

### Node.js version

18.14.2

### Package manager

npm

### Operating system

Windows

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by jfstephe** [comment]
ok - so I was right in that there was something that I was missing - I'll close this ticket, but for future reference.

My use case was using cucumberjs to run tests using @testing-library/react

I use tsx to do the transpilation (tried with ts-node too but tsx covered more cases).

NODE OPTIONS needed to include: "--loader tsx --loader esm-loader-css" and a custom loader using css-modules-require-hook/preset

esm-loader-css takes care of:

import "foo.css"

the custom loader takes care of:

import cssModule from "bar.modules.css";

Sorry for my ignorance but hopefully this helps someone else!
