### ISSUE TITLE
INFORMATION FOR OTHERS!

### ISSUE THREAD

**Issue by Tomato6966** [esbuild-kit/tsx#323]
I had this problem:
```

node:internal/process/esm_loader:48
      internalBinding('errors').triggerUncaughtException(
                                ^
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/projects/Mivator/Dev/node_modules/escalade/sync/index.mjs' imported from /home/projects/Mivator/Dev/node_ms
Did you mean to import escalade/sync/index.js?
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:224:11)
    at moduleResolve (node:internal/modules/esm/resolve:836:10)
    at defaultResolve (node:internal/modules/esm/resolve:1034:11)
    at nextResolve (node:internal/modules/esm/hooks:832:28)
    at E (file:///home/projects/Mivator/Dev/node_modules/tsx/dist/loaders-deprecated-261ba186.mjs:12:49)
    at D (file:///home/projects/Mivator/Dev/node_modules/tsx/dist/loaders-deprecated-261ba186.mjs:12:1279)
    at nextResolve (node:internal/modules/esm/hooks:832:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:277:30)
    at handleMessage (node:internal/modules/esm/worker:168:24)
    at checkForMessages (node:internal/modules/esm/worker:117:28)
    at process.<anonymous> (node:internal/modules/esm/worker:136:5)
    at process.emit (node:events:514:28)
    at process.emit (node:domain:488:12) {
  url: {},
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v20.7.0

node:internal/process/esm_loader:48
      internalBinding('errors').triggerUncaughtException(
                                ^
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/projects/Mivator/Dev/node_modules/escalade/sync/index.mjs' imported from /home/projects/Mivator/Dev/node_ms
Did you mean to import escalade/sync/index.js?
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:224:11)
    at moduleResolve (node:internal/modules/esm/resolve:836:10)
    at defaultResolve (node:internal/modules/esm/resolve:1034:11)
    at nextResolve (node:internal/modules/esm/hooks:832:28)
    at E (file:///home/projects/Mivator/Dev/node_modules/tsx/dist/loaders-deprecated-261ba186.mjs:12:49)
    at D (file:///home/projects/Mivator/Dev/node_modules/tsx/dist/loaders-deprecated-261ba186.mjs:12:1279)
    at nextResolve (node:internal/modules/esm/hooks:832:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:277:30)
    at handleMessage (node:internal/modules/esm/worker:168:24)
    at checkForMessages (node:internal/modules/esm/worker:117:28)
    at process.<anonymous> (node:internal/modules/esm/worker:136:5)
    at process.emit (node:events:514:28)
    at process.emit (node:domain:488:12) {
  url: {},
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v20.7.0
/home/projects/Mivator/Dev/node_modules/discord-hybrid-sharding/dist/Core/Cluster.js:151
                reject(new Error('CLUSTERING_READY_DIED | ClusterId: ' + this.id));
                       ^

Error: CLUSTERING_READY_DIED | ClusterId: 0
    at Cluster.onDeath (/home/projects/Mivator/Dev/node_modules/discord-hybrid-sharding/dist/Core/Cluster.js:151:24)
    at Object.onceWrapper (node:events:629:26)
    at Cluster.emit (node:events:514:28)
    at Cluster._handleExit (/home/projects/Mivator/Dev/node_modules/discord-hybrid-sharding/dist/Core/Cluster.js:280:14)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
Emitted 'error' event on Cluster instance at:
    at /home/projects/Mivator/Dev/node_modules/discord-hybrid-sharding/dist/Core/Cluster.js:289:44
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.7.0
```

project is a discord bot using discord-hybrid-sharding and puppeteer and @discordjs/voice

with package.json#type = "module";
with the following tsconfig
```
{
    "compilerOptions": {
        "target": "ESNext",
        "module": "ESNext",
        "lib": ["ESNext"],
        "moduleResolution": "Node",
        "outDir": "./dist",
        "rootDir": "./src",
        "baseUrl": ".",
        "allowJs": true,
        "noEmit": true,
        "skipLibCheck": true,
        "importHelpers": true,
        "resolveJsonModule": true,
        "esModuleInterop": true,
        "allowImportingTsExtensions": true,
        "allowSyntheticDefaultImports": true,
        "forceConsistentCasingInFileNames": true,
        "types": [ "node", "ws" ]
    },
    "include": [ 
        "src/**/*.ts"
    ],
    "lib": ["ESNext"],
    "exclude": [
      "node_modules",
      "dist"
    ]
  }
```

I was confused why that error happened, cause it just "changed" the package's import from "file.js" to "file.mjs"

It leads to some cache / node_modules error
i did this and it fixed it!

```
npm cache clear --force
rm node_modules -r && npm install
```

Thanks for this amazing project!
*In addition people can use this tsconfig for a process based (childprocess forking) discord bot sharder*

### Motivations

I moved from ts-node to tsx cause ts-node was not able to run esnext project as a module
it kept saying "unknown file extension.ts"

**Comment by Tomato6966** [comment]
You can mark it as solved!
