### ISSUE TITLE
Cleaner build-time errors

### ISSUE THREAD

**Issue by colinking** [esbuild-kit/tsx#339]
### Feature request

Ideally the error messages produced by `tsx` when building code could be formatted more clearly.

Consider a file, `entrypoint.ts`, with a missing parenthesis:

```
const main = () => {
  console.log("Hello world!";
}

main()
```

When executed, `tsx` provides the following error:

```
$ npx tsx ./entrypoint.ts
node:internal/process/esm_loader:108
    internalBinding('errors').triggerUncaughtException(
                              ^

Error: Transform failed with 1 error:
/Users/colin/dev/github.com/airplanedev/testing/tsx/entrypoint.ts:2:28: ERROR: Expected ")" but found ";"
    at failureErrorWithLog (/Users/colin/.npm/_npx/fd45a72a545557e9/node_modules/esbuild/lib/main.js:1649:15)
    at /Users/colin/.npm/_npx/fd45a72a545557e9/node_modules/esbuild/lib/main.js:847:29
    at responseCallbacks.<computed> (/Users/colin/.npm/_npx/fd45a72a545557e9/node_modules/esbuild/lib/main.js:703:9)
    at handleIncomingPacket (/Users/colin/.npm/_npx/fd45a72a545557e9/node_modules/esbuild/lib/main.js:762:9)
    at Socket.readFromStdout (/Users/colin/.npm/_npx/fd45a72a545557e9/node_modules/esbuild/lib/main.js:679:7)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:335:12)
    at readableAddChunk (node:internal/streams/readable:308:9)
    at Readable.push (node:internal/streams/readable:245:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 28,
        file: '/Users/colin/dev/github.com/airplanedev/testing/tsx/entrypoint.ts',
        length: 1,
        line: 2,
        lineText: '  console.log("Hello world!";',
        namespace: '',
        suggestion: ')'
      },
      notes: [],
      pluginName: '',
      text: 'Expected ")" but found ";"'
    }
  ],
  warnings: []
}

Node.js v18.18.0
```

The underlying issue is within the stack trace (specifically `entrypoint.ts:2:28: ERROR: Expected ")" but found ";"`), but there's a lot of additional information that makes that hard to find. Most notably, the unrelated `esm_loader:108` error, the stack trace composed of unrelated node/esbuild lines, and the JSON blob that's concatenated to the stack trace.

FWIW, the error messages produced by runtime errors are great. My concern only applies to the errors produced by build errors.

### Motivations

We'd like to build user-provided code and provide easy-to-debug error messages to the user if their code fails to compile. 

### Alternatives

We could parse the error from the JSON blob and pretty-print it ourselves, but I figure the format could change which could break our custom formatting.

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
Sounds like a pretty straightforward improvement. Happy to accept a PR!

I'd expect the errors to look similar to Node.js or TypeScript's if possible.
