### ISSUE TITLE
Cannot use tsx/cjs loader in custom  command line.

### ISSUE THREAD

**Issue by yzqdev** [esbuild-kit/tsx#369]
### Precheck

- [X] I searched existing issues before opening this one to avoid duplicates
- [X] I'm able to reproduce this issue and prove it with a minimal reproduction
- [X] I understand this is not a place to ask for free debugging support

## my minimal project url [https://github.com/yzqbugs/tsx-bug](https://github.com/yzqbugs/tsx-bug)

run `yarn buld:cjs`,the script is ` gulp --require @esbuild-kit/cjs-loader`,there is no error.

while run `yarn buld:tsx`,the script is `gulp --require tsx/cjs`,there is a error. 

so i guess tsx causes this error.

```
√ script to run » build:tsx
[19:28:19] Failed to load external module tsx/cjs
[19:28:19] Error: Cannot find module 'tsx/cjs' from 'E:\WebstormProjects\tsx-bug'
[19:28:19] Failed to load external module ts-node/register
[19:28:19] Error: Cannot find module 'ts-node/register' from 'E:\WebstormProjects\tsx-bug'
[19:28:19] Failed to load external module typescript-node/register
[19:28:19] Error: Cannot find module 'typescript-node/register' from 'E:\WebstormProjects\tsx-bug'
[19:28:19] Failed to load external module typescript-register
[19:28:19] Error: Cannot find module 'typescript-register' from 'E:\WebstormProjects\tsx-bug'
[19:28:19] Failed to load external module typescript-require
[19:28:19] Error: Cannot find module 'typescript-require' from 'E:\WebstormProjects\tsx-bug'
[19:28:19] Failed to load external module sucrase/register/ts
[19:28:19] Error: Cannot find module 'sucrase/register/ts' from 'E:\WebstormProjects\tsx-bug'
[19:28:19] Failed to load external module @babel/register
[19:28:19] Error: Cannot find module '@babel/register' from 'E:\WebstormProjects\tsx-bug'
E:\WebstormProjects\tsx-bug\gulpfile.ts:1
import gulp from "gulp";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at requireOrImport (E:\WebstormProjects\tsx-bug\node_modules\gulp-cli\lib\shared\require-or-import.js:19:11)
    at execute (E:\WebstormProjects\tsx-bug\node_modules\gulp-cli\lib\versioned\^4.0.0\index.js:37:3)
```

## my minimal project url [https://github.com/yzqbugs/tsx-bug](https://github.com/yzqbugs/tsx-bug)
there are only three files
## package.json
```json
{
  "name": "tsx-bug",
  "version": "0.0.2",
  "license": "MIT",
  "scripts": {
    "build:cjs": " gulp --require @esbuild-kit/cjs-loader",
    "build:tsx": " gulp --require tsx/cjs"
  },
  "devDependencies": {
    "@esbuild-kit/cjs-loader": "^2.4.4",
    "@types/gulp": "^4.0.16",
    "@types/node": "^18.18.8",
    "gulp": "^4.0.2",
    "prettier": "^3.0.3",
    "tsx": "^3.14.0",
    "typescript": "^5.2.2"
  }
}
```

gulpfile.ts
```ts
import gulp from "gulp";
 
gulp.task("default", async () =>{
    console.log("Hello World!");
});
```

tsconfig.json
```json

{
  "compilerOptions": {
    "sourceMap": true,
    "outDir": "dist",
    "target": "ES2015",
    "module": "ES2015",
    "moduleResolution": "Bundler",
    "strict": false,
    "lib": ["esnext"],
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "esModuleInterop": true,
    "verbatimModuleSyntax": true,
    "resolveJsonModule": true
  }
}
```

### Expected behavior

command line can run without error

### Minimal reproduction URL

https://github.com/yzqbugs/tsx-bug

### Version

^3.14.0

### Node.js version

v18.18.0

### Package manager

yarn

### Operating system

Windows

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
Thanks for the issue and reproduction.

There doesn't seem to be a tsx bug here though. You can confirm expected behavior via:
```
node --require tsx/cjs gulpfile.ts
```

The limitation seems to be in gulp not supporting export maps. Please file an issue there.

**Comment by yzqdev** [comment]
Thank you. I just solved it by using `node  --require tsx/cjs node_modules/gulp-cli/bin/gulp.js` command line.
