### ISSUE TITLE
alwaysStrict not respected

### ISSUE THREAD

**Issue by tonyxiao** [esbuild-kit/tsx#64]
### Bug description

Esbuild supports the alwaysStrict compiler option https://github.com/evanw/esbuild/blob/9860ee3b1ff83b7c6e8889e96da42add36d50ba3/internal/resolver/tsconfig_json.go#L40

However this does not appear to be supported in tsx. 

It's possible that this is related to https://github.com/nodejs/node/issues/30039

### Reproduction

```bash
❯ cat tsconfig.json
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "display": "Expo",
  "compilerOptions": {
    "module": "esnext",
    "noUnusedLocals": true,
    "allowJs": true,
    "esModuleInterop": true,
    "jsx": "preserve",
    "lib": [
      "DOM",
      "ESNext"
    ],
    "moduleResolution": "node",
    "noEmit": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "target": "ESNext",
    "strict": true,
    "noUncheckedIndexedAccess": true,
    "alwaysStrict": true
  },
  "include": [
    "./custom",
    "./next/universal",
    "./next/pages"
  ],
  "exclude": [
    "node_modules",
    "babel.config.js",
    "metro.config.js",
    "jest.config.js"
  ],
  "extends": "expo/tsconfig.base"
}
❯ cat test.ts

const obj = Object.freeze({name: 'Elsa', score: 157});
obj.name = 'aaa'
❯ tsx test.ts
```
This passes. I would however expect an error. 

If i manually add a `use strict` to the top of the ts file then it will crash as expected

```bash
❯ cat test.ts
'use strict'
const obj = Object.freeze({name: 'Elsa', score: 157});
obj.name = 'aaa'
❯ tsx test.ts
obj.name = 'aaa'
    ^

TypeError: Cannot assign to read only property 'name' of object '#<Object>'
    at Object.<anonymous> (.../test.ts:3:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.m (/Users/tony/.nvm/versions/node/v16.13.1/lib/node_modules/tsx/node_modules/@esbuild-kit/cjs-loader/dist/index.js:1:536)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:190:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5)

```

### Environment

```shell
System:
    OS: macOS 12.3
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.34 GB / 64.00 GB
    Shell: 3.5.0 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment]
[Fixed in esbuild v0.15.8](https://hyrious.me/esbuild-repl/?version=0.15.8&mode=transform&options=--loader%3Dts+--format%3Dcjs+--tsconfig-raw%3D%27%7B+%22compilerOptions%22%3A+%7B%22alwaysStrict%22%3A+true%7D+%7D%27)

However, this leads to a bug in tsx where all dependencies getting compiled in strict mode. Will fix.
